[project]
name = "localai-flask-app"

[[services]]
name = "flask-api"
start = { cmd = "gunicorn --bind 0.0.0.0:8000 app:app" }
build = { dockerfile = "Dockerfile" }

[[services]]
name = "localai"
start = { cmd = "local-ai --models-path /models --config-file /models/models.yaml --host 0.0.0.0 --port 8080" }
build = { dockerfile = "Dockerfile" }
